### ISSUE TITLE
Generate UMD bundle from tsickle output?

### ISSUE THREAD

**Issue by trxcllnt** [angular/tsickle#534]
I'm working on the new build for [IxJS v2](https://github.com/reactivex/ixjs), which if all goes well we may back-port to RxJS. I have tsickle successfully compiling the TS source to goog modules for closure-compiler, which is great.

Next I was hoping I could run closure-compiler with advanced opts on the tsickle output to create the UMD bundle, but I'm stuck on the details of the magic incantation that convinces closure-compiler it really wants to to do this for me.

Do you guys have any examples of building a UMD bundle from tsickle output? Is this even a reasonable approach? My fallback plan is to run rollup and closure-compiler together, but then I'm stuck with simple opts :<

**Comment by evmar** [comment]
You're trying to create a UMD bundle just from your library?  I think the approach to take is

1) use closure compiler to generate a small bundle
2) wrap that bundle with whatever UMD magic you like

You could maybe use the output-wrapper feature of the compiler to do that in one step, see an example here:
https://stackoverflow.com/questions/39847332/google-closure-compiler-and-umd-pattern

(But note that part of the point of using the compiler is to give it *all* the code to compile together, so it can (for example) delete the unused parts of your library in the user's final bundle.  So generating the intermediate bundle isn't as valuable there.  But I guess the reason to make a UMD bundle is for users who aren't using the compiler?  In which case I think you're on the right track!)

**Comment by trxcllnt** [comment]
> @evmar But I guess the reason to make a UMD bundle is for users who aren't using the compiler?

Yes, exactly. We'll still have the source goog modules version available, and want to build the browser UMD bundle from those.

Unfortunately I haven't had success throwing the closure-compiler at the raw goog source and using the `output_wrapper` option, since the closure-compiler mangles the names of the exports.

**Comment by evmar** [comment]
Yep, it mangles anything you don't explicitly tell it to not mangle.  (That's also why it works better when you give it the whole program -- it's safe to mangle there because it can see all the code.)

One thing you might try is remove tsickle from the equation to start with.  Make a simple .js file and feed it to the compiler and play with it until it generates what you want.  For example, one piece I don't understand is what code is generated for functions that are exported from your UMD module.  Is there an exports object there?  So write some file like

```js
function longNameShouldBeMangled() { return 3; }
export function publicApi() { return 4; }
```

and then see what the compiler generates (ensure the output has that "publicApi" function in it unmangled).  I think it might be that you write a comment like 
```js
function longNameShouldBeMangled() { return 3; }
/** @export */
export function publicApi() { return 4; }
```
Though I'm not totally sure.

This section of the docs is relevant:
https://developers.google.com/closure/compiler/docs/api-tutorial3#no
You might also ask on their mailing list about it, especially if you just have a .js file that you're trying to make work.

Once you understand what JS you want, I can help you figure out if tsickle is generating the wrong thing or not.

**Comment by trxcllnt** [comment]
@evmar ah, yeah let me take it from the top:

Our lib entry point for tsickle is [`src/Ix.ts`](https://github.com/ReactiveX/IxJS/blob/master/src/Ix.ts#L3), which has these exports:

```typescript
export { IterableX as Iterable } from './iterable';
export { AsyncIterableX as AsyncIterable } from './asynciterable';
```

Then we run tsickle with this command (our normal tsconfig has different module/target defs, so we override them for tsickle):
```bash
$ tsickle --externs targets/es5/google/Ix.externs.js --typed -- -p . -m commonjs --target ES5 --outDir targets/es5/google
```

The corresponding tsickle output for that file starts like this:
```javascript
goog.module('targets.es5.google.Ix'); exports = {}; var module = {id: 'targets/es5/google/Ix.js'};/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */

var iterable_1 = goog.require('targets.es5.google.iterable');
exports.Iterable = iterable_1.IterableX;
var tsickle_forward_declare_1 = goog.forwardDeclare('_Users.ptaylor.dev.ixjs.source.iterable');
var asynciterable_1 = goog.require('targets.es5.google.asynciterable');
exports.AsyncIterable = asynciterable_1.AsyncIterableX;
var tsickle_forward_declare_2 = goog.forwardDeclare('_Users.ptaylor.dev.ixjs.source.asynciterable');
```

Are you recommending we add `/* @export */` comments to the source TS code?

**Comment by evmar** [comment]
I suggest taking a small snippet of JS file and fiddling with it manually until closure compiler does what you want, because I'm not sure exactly how to make it do what you want.  And then once you figure that out, comment here with what the fix will be.  Maybe tsickle could insert the @export lines for you, for example, if we think that is what you need.

**Comment by trxcllnt** [comment]
I'm able to compile a UMD bundle with the java version of CC. There's some coupling between the UMD wrapper and the source file. It's unclear whether the extra code will break other bundlers, but I'm able to create a UMD bundle

Using this as CC's output_wrapper (the `Ix` exports arg is key):
```javascript
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
	typeof define === 'function' && define.amd ? define(['exports'], factory) :
	(factory(global.Ix = global.Ix || {}));
}(this, (function (exports) {
  %output%
  return exports;
}.bind(this))));
```

Then in the source TS entry file (`source/Ix.ts`), explicitly re-export on the UMD export:
```typescript
try {
  const Ix = eval('exports || (exports = {})');
  Ix['Iterable'] = IterableX;
  Ix['AsyncIterable'] = AsyncIterableX;
} catch (e) { /* not the UMD bundle */ }
```

This new `if` condition will be included in all compilation targets. I get a reference to the exports argument via eval, so bundlers that that strictly enforce var declaration for `typeof` statements (*cough* closure compiler *cough) can still bundle our other output targets. The eval also has to do `|| exports = {}` because (from my understanding) requireJS doesn't guarantee exports is initialized.

**Comment by evmar** [comment]
I didn't quite follow you there -- which "if" condition?  I see no "if"?

Instead of `eval('exports')`, you might try `goog.exportSymbol('exports.Iterable', IterableX);`.  Not sure if that will work (the "exports" symbol is special in Closure code).  You might also double check whether the properties of `IterableX` have been renamed (e.g. if it has any methods they might have been mangled).

**Comment by trxcllnt** [comment]
@evmar I did try manually adding `goog.exportSymbol()` to the tsickle output, but that didn't prevent CC from mangling the name either. Additionally I can't justify inserting it into the _source_ TS, since we compile the TS to multiple JS versions/module formats (es5/es6/esnext x commonjs/es-modules/systemjs/closure/umd).

> You might also double check whether the properties of IterableX have been renamed (e.g. if it has any methods they might have been mangled).

I did a spot check, and it seems all static and proto props aren't renamed during the UMD bundle, so I think we're good. Overall this does seem like a problem that would benefit from tooling. I'll leave it to the tsickle team as to whether this is something they would like to include.

**Comment by evmar** [comment]
@trxcllnt goog.exportSymbol does cause the symbol to get mangled, but it exports the mangled symbol under the unmangled name

e.g. `goog.exportSymbol('foo.bar', foo.bar)` might become `goog.exportSymbol('foo.bar', a.b)`, but then the implementation of `goog.exportSymbol` (which will be inlined into the output) will insure that a `foo.bar` exists at the end.

Can you describe the tooling you'd like here?  I still am not sure if your problem is solved or not.  :)  It seems it would be at least worth writing up what you ended up with in the tsickle docs.

**Comment by Addeventure** [comment]
A bit late perhaps, but if anyone stumbles upon this... 
Another approach that worked successfully for me was to simply declare a variable as extern in typescript and then declaring it in the UMD factory function. This allows to export a library without polluting the global namespace and no eval required. 

In your index.ts or whatever:
```
// Export public api
declare let libExports: { [key: string]: any}; // Or a declared interface

libExports['SomeClass'] = SomeClass;
libExports['someFunction'] = someFunction;
```

In the closure output wrapper:
```
 (function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        define([], factory);
    } else if (typeof module === 'object' && module.exports) {
        module.exports = factory();
    } else {
        root.reflow = factory();
  }
}(typeof self !== 'undefined' ? self : this, function () {
  var libExports = {};
  %output%
  return libExports;
}));`
```
