### ISSUE TITLE
Inlining const enum broken

### ISSUE THREAD

**Issue by jasonaden** [angular/tsickle#593]
As of version `0.23.4`, inlining of `const enum`s no longer works. This likely will be fixed with the new endpoint, but the [enum test](https://github.com/angular/tsickle/blob/master/test_files/enum/enum.js) should be checking for this behavior.

**Comment by mprobst** [comment]
I believe this is WAI to make type checking using Closure Compiler succeed. What problem does this cause?

**Comment by IgorMinar** [comment]
This has been fixed in a subsequent tsickle release.

I just confirmed that const enum `QueryBindingType` was not inlined in [@angular/core@5.0.0-beta.6](https://unpkg.com/@angular/core@5.0.0-beta.6/esm5/index.js) but it was inlined in later releases like [5.0.0-beta.7](https://unpkg.com/@angular/core@5.0.0-beta.7/esm5/index.js) or the most [recent rc](https://unpkg.com/@angular/core@5.0.0-rc.2/esm5/core.js)
