### ISSUE TITLE
Tsickle should tag releases

### ISSUE THREAD

**Issue by LucasSloan** [angular/tsickle#594]
I was just asked how to find the state of the repo as of a given npm release.  We can manually walk the package.json history, but we should figure out a process to ensure we get a tagged branch when the release happens.

**Comment by mprobst** [comment]
Maybe we should have a `release.sh` script that just calls `npm release
...` with the right args?

**Comment by LucasSloan** [comment]
That's my hope, yes.

**Comment by mprobst** [comment]
I've looked into this because I just needed to release. It's really too trivial to add a script - you run `npm version minor|major|... -m 'rel: %s.'`, done, including tag. Give that the version would need to stay a parameter, it seems like a script won't pull its own weight. I'll send an email to the team to raise awareness.
