### ISSUE TITLE
Question: Tsickle + typesript jsdoc

### ISSUE THREAD

**Issue by wardpeet** [angular/tsickle#651]
I've started to use closure compiler as an alternative to uglify. I'm only to using it to optimise my scripts. Lately I've looked at typescript and how it would fit my workflow. I'm now using typescript type checking with JSDoc. Can I still use tsickle to optimise my javascript files with annotations?

**Comment by mprobst** [comment]
Generally speaking yes. tsickle reads TypeScript and emits JavaScript that has `/** jsdoc */` annotations that are compatible with Closure Compiler.

It turns out in practice it's a bit hard to use by itself, as a number of things have to align properly, in particular around rootDir and outDir and some such.

@alexeagle is working on open sourcing the integration, he might have some advice what's the easiest way to get started these days.

**Comment by evmar** [comment]
Obsolete.
