### ISSUE TITLE
Allow @implements of 'abstract class'

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#885]
This allows a DI pattern

```ts
abstract class IFace { ... }
di.register(IFace, ...); /// <- IFace must be a class for it to have a value

class Foo implements IFace {}
```

Currently tsickle drops the 'implements IFace' because you cannot implements a class, but in the specific case of an empty abstract class we could allow it.

**Comment by mprobst** [comment]
Aren't we emitting the abstract class as `/** @constructor @abstract */
class IFace {}`? Wouldn't Closure complain about implementing a class?

Btw this is the one dangerous are in Closure, when you get inheritance
wrong, with disambiguate properties Closure will actually incorrectly
optimize instead of backing off, I believe.

Alternatively, we could exactly match TypeScript's understanding of the
world and for each "class Foo" emit `/** @implements {Foo_Interface} */
class Foo` and `/** @record */ class Foo_Interface {}`, similar to what we
do in Clutz for ES6 instance vs class side. That will generate a ton of
dup'ed code though.

**Comment by evmar** [comment]
Right, what I'm suggesting here is that we emit 

```js
/** @interface */
class C { ... }
```

when we have an abstract class.  It's confusing because both TS and Closure are using the terms 'class and 'interface' with different meanings.  I think this approach better matches the Closure semantics.

**Comment by jplaisted** [comment]
So what happens if you have an actually abstract class that you `extend` in TS rather than `implement`? tsickle has to know all usages of the abstract class to determine if it should be emitted as an `@interface` or not, right?

**Comment by evmar** [comment]
I was assuming you could 'extends' the class, despite the @interface tag, but I now see that doesn't work.  Hm.  I think I'm beginning to understand why Angular uses a different pattern for DI.

**Comment by jplaisted** [comment]
Personally I don't like Angular's DI (`toString`ing a method to regex the implementation really doesn't feel right to me, but to each their own I guess).

I prefer the model of passing around keys to the DI to get values.

Really the issue here is that TypeScript decided interface are always and forever a type concept and can never exist in emitted code. And this DI pattern uses the interface as the key. Closure is looser, you can actually reference interfaces. If you only reference the interface in type annotations it gets stripped, but if you reference it in code it won't (e.g. passing to DI, static methods on the interface, etc).

**Comment by evmar** [comment]
Nah I'm talking about this Angular: https://angular.io/api/core/InjectionToken , which is passing around keys.

**Comment by jplaisted** [comment]
Ah, okay, that's better. I admittedly don't know much about Angular, I thought its main DI was via `$dollarParamNames`, which I assumed Angular would use regexes to find. Did I just totally misunderstand that, or was that dropped with the move to Angular 2? Decorators a bit better, but they aren't in JS (and I disagree with the current JS proposals).

Anyway, that's besides the point. It seems to me that seeing if the users can write some new TS code that fits TS idioms may be a better approach than trying to get tsickle to cover this, since it seems pretty difficult.

**Comment by evmar** [comment]
Oops, I overlooked your above question about global usage.  We don't have this sort of info because we want compilation to behave locally.

I think we cannot do something clever here.  I'm gonna close this and think about it more.

**Comment by evmar** [comment]
Oops, and now I overlooked your Angular 2 question.  You are right that AngularJS did some crazy regex stuff.  Angular2 is effectively totally different, a complete rewrite.
