### ISSUE TITLE
"anonymous abstract function" with symbol-identified methods

### ISSUE THREAD

**Issue by Yogu** [angular/tsickle#913]
The following code:

```typescript
export interface AccessorBase<T> {
    readonly $accessPath: AccessPath<any, T>;
    readonly $parent: ObjectAccessor<{}> | ListAccessor<object> | undefined;

    [accessPathSymbol](): AccessPath<any, T>;
}
```

generates the error *anonymous abstract function*. This is most likely the case because [ `propertyName`](https://github.com/angular/tsickle/blob/9f47abe532473895db3c494ff5a3266696472b4b/src/jsdoc_transformer.ts#L313) only considers identifiers and string literals, and not symbols. I have not checked, but I would gess `['methodName'](): string` causes the same error.

The problem has been introduced in version 0.33.0 - 0.32.1 works.

**Comment by evmar** [comment]
Can you include the specific error?  I'm not sure from your report which piece is failing.

**Comment by Yogu** [comment]
That is the exact error message (in the issue title), and it's thrown in the file I linked.

**Comment by evmar** [comment]
So you're encountering something like:

```
$ some_command_here
anonymous abstract function
```

and that is the total output?

**Comment by evmar** [comment]
Ah, it's probably this: https://github.com/angular/tsickle/blob/acaac91f460e5351262506c29b60ccc7f3ec25b6/src/jsdoc_transformer.ts#L285

From the original report it sounded like JSCompiler was failing.

**Comment by Yogu** [comment]
Ah sorry, I forgot to specify that it generates a Typescript error with this message in ng build. The line you linked is my best guess for the error location, too. Is it clear now? There is just a branch missing for the [...] property syntax.

**Comment by evmar** [comment]
The code you linked to is generating the Closure-equivalent property name given a TypeScript field, but I believe there is no Closure-equivalent property name for the syntax you're using, so the solution will probably be in a different place.

**Comment by Yogu** [comment]
Oh,ok. Maybe it needs to be fixed further up in the angular build stack.
@kroeder can you post the stack trace?

Evan Martin <notifications@github.com> schrieb am Mi., 17. Okt. 2018, 20:52:

**Comment by evmar** [comment]
Nah I think we have enough info, thanks.  I think this pattern is basically inexpressible in Closure and we don't have a good answer for it.

**Comment by evmar** [comment]
It looks like for other inexpressible fields we just drop them and hope for the best:

https://github.com/angular/tsickle/blob/acaac91f460e5351262506c29b60ccc7f3ec25b6/test_files/interface/interface.js#L60

**Comment by kroeder** [comment]
> Nah I think we have enough info, thanks. I think this pattern is basically inexpressible in Closure and we don't have a good answer for it.

I'm wondering why our code works in `0.32.0` but is broken in `0.33.0` and `0.34.0` 

I understand this might be an edge-case issue but I still wanted to mention that this prevents (can't be just us?) people using `ng update` in angular projects because it wants `0.32.0 >` and on the other side `ng update` is the only migration info you get when you want to update your angular nowadays (that's the case for version 6 to 7)

So people (we? 😄 ) have to manually figure out what has changed in Angular in pretty odd ways

**Comment by ribrdb** [comment]
Is this really inexpressible in closure? How is it different from the Symbol methods in https://github.com/google/closure-compiler/blob/50713dceb16b369f8f317e5b49e8a9dec2b47496/externs/es6_collections.js

Couldn't you just do
```js
/** @returns {AccessPath<*,T>}*/
AccessorBase.prototype[accessPathSymbol] = function();
```

I tried manually generating this code and the closure compiler seems to accept it.
So I think you could fix this in tsickle/src/jsdoc_transformer.ts:
If `fnDecl.name.kind == ts.SyntaxKind.ComputedPropertyName`,
use `ts.createElementAccess(instancePropAccess, fnDecl.name.expression)` instead of `ts.createPropertyAccess(instancePropAccess, name)`

**Comment by ayazhafiz** [comment]
@ayazhafiz
